ASPNETFastpathTraining/Pages/Modul02/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNETFastpathTraining.Pages.Modul02
{
    public class IndexModel : PageModel
    {
        public string Variable = "Tets";
        public void OnGet()
        {


        }
        public void OnPost() {
         Variable=   Request.Form["input1"];
        }    
    }
}

ASPNETFastpathTraining/Pages/Modul02/PageState.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNETFastpathTraining.Pages.Modul02
{
    public class PageStateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ASPNETFastpathTraining/Pages/Modul02/Route2.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNETFastpathTraining.Pages.Modul02
{
    public class Route2Model : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ASPNETFastpathTraining/Pages/Modul02/RoutenSample.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNETFastpathTraining.Pages.Modul02
{
    public class RoutenSampleModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ASPNETFastpathTraining/Pages/Modul02/ShowSession.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNETFastpathTraining.Pages.Modul02
{
    public class ShowSessionModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ASPNETFastpathTraining/Pages/Modul02/SitzungsStatus.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNETFastpathTraining.Pages.Modul02
{
    public class SitzungsStatusModel : PageModel
    {
        public void OnGet()
        {
        }
        public void OnPost() {
            HttpContext.Session.SetString("hannes", Request.Form["input1"]);
            Response.Redirect("/session2");
        }
    }
}

ASPNETFastpathTraining/Pages/Modul02/Taschenrechner.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNETFastpathTraining.Pages.Modul02
{
    public class TaschenrechnerModel : PageModel
    {
        [BindProperty()]
        public float input1 { get; set; }
        [BindProperty()]
        public float input2 { get; set; }

        public double Ausgabe;

        public void OnGet()
        {
        }
        
        public void OnPostAdd() {


            Ausgabe=input1 + input2;
        }
        public void OnPostSub()
        {


            Ausgabe = input1 - input2;
        }

    }
}

ASPNETFastpathTraining/Pages/Modul03/Taschenrechner.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPNETFastpathTraining.Pages.Modul03
{
    public class TaschenrechnerModel : PageModel
    {
        [BindProperty()]
        public float input1 { get; set; }
        [BindProperty()]
        public float input2 { get; set; }

        public double Ausgabe;

        public void OnGet()
        {
        }
        
        public void OnPostAdd() {


            Ausgabe=input1 + input2;
        }
        public void OnPostSub()
        {


            Ausgabe = input1 - input2;
        }

    }
}

ASPNETFastpathTraining/Pages/Modul02/Index.cshtml
@page
@model ASPNETFastpathTraining.Pages.Modul02.IndexModel
<div id="div1" style="color:@Model.Variable">
    @Model.Variable
    </div>
<hr />
<form method="post">
    <input id="input1" name="input1" value="@Model.Variable" />
    <button type="submit">send</button>
</form>


@{
}

ASPNETFastpathTraining/Pages/Modul02/PageState.cshtml
@page "/status"
@model ASPNETFastpathTraining.Pages.Modul02.PageStateModel
@{
    ViewData["Title"] = "ViewData";
}

ASPNETFastpathTraining/Pages/Modul02/Route2.cshtml
@page
@model ASPNETFastpathTraining.Pages.Modul02.Route2Model
@{
}
<a asp-page="/modul02/Routensample"
   asp-route-hersteller="Audi"
   asp-route-typ="A5"
   asp-route-ps="170">Audi A5  Cabrio braun 170PS</a>
<a asp-page="/modul02/Routensample" asp-route-id="2">Click</a>

ASPNETFastpathTraining/Pages/Modul02/RoutenSample.cshtml
@page "/Autos/{hersteller?}/{typ?}/{ps:int?}"
@model ASPNETFastpathTraining.Pages.Modul02.RoutenSampleModel

<h1>@RouteData.Values["hersteller"]</h1>

<a asp-page="/modul02/Routensample"
   asp-route-hersteller="Audi"
   asp-route-typ="A5"
   asp-route-ps="170">Audi A5  Cabrio braun 170PS</a>

@{
}

ASPNETFastpathTraining/Pages/Modul02/ShowSession.cshtml
@page "/session2"
@model ASPNETFastpathTraining.Pages.Modul02.ShowSessionModel

<h1>@HttpContext.Session.GetString("hannes")</h1>
@{
}

ASPNETFastpathTraining/Pages/Modul02/SitzungsStatus.cshtml
@page "/session"
@model ASPNETFastpathTraining.Pages.Modul02.SitzungsStatusModel

<form method="post">
    <input id="input1" name="input1"  />
    <button type="submit">send</button>
</form>

@{
}

ASPNETFastpathTraining/Pages/Modul02/Taschenrechner.cshtml
@page "/calc/{handler?}"
@model ASPNETFastpathTraining.Pages.Modul02.TaschenrechnerModel
@{
}

<form method="post" >
    <input type="number" step="0.01" min="1" max="10000000" name="input1" />
    <input  name="input2" />
    <button  asp-page-handler="add">+</button>
    <button asp-page-handler="sub">-</button>
</form>
<hr />
@Model.Ausgabe